JUMP_PARAMS = {
    "forward": {
        "IMPULSE_F0": 3.8,
        "IDLE_F1": 1.0,
        "FORCE_FX": 140.0,
        "FORCE_FY": 0.0,
        "FORCE_FZ": 370.0,
        "N_JUMPS": 12,
        "KP_XY": 280.0,
        "KP_Z": 1200.0,
        "KD_FLIGHT_XY": 8.0,
        "KD_FLIGHT_Z": 8.0,
        "KD_STANCE_XY": 40.0,
        "KD_STANCE_Z": 150.0,
    },
    "lateral": {
        "IMPULSE_F0": 3.8,
        "IDLE_F1": 1.0,
        "FORCE_FX": 0.0,
        "FORCE_FY": 140.0,
        "FORCE_FZ": 370.0,
        "N_JUMPS": 12,
        "KP_XY": 1900.0,
        "KP_Z": 1300.0,
        "KD_FLIGHT_XY": 22.0,
        "KD_FLIGHT_Z": 22.0,
        "KD_STANCE_XY": 50.0,
        "KD_STANCE_Z": 270.0,
    },
    "twist": {
        "IMPULSE_F0": None,
        "IDLE_F1": None,
        "FORCE_FX": None,
        "FORCE_FY": None,
        "FORCE_FZ": None,
        "N_JUMPS": None,
        "KP_XY": None,
        "KP_Z": None,
        "KD_FLIGHT_XY": None,
        "KD_FLIGHT_Z": None,
        "KD_STANCE_XY": None,
        "KD_STANCE_Z": None,
    }
}
